=== room-end/catalog/catalog.viewer/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="catalog">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="year"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="year">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="film"/>
			</xs:sequence>
			<xs:attribute name="y" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="film">
		<xs:complexType>
			<xs:attribute name="number" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1001"/>
						<xs:maxInclusive value="4999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="author" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ivana"/>
						<xs:enumeration value="roumen"/>
						<xs:enumeration value="silvia"/>
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="camera" type="xs:string" />
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="fn"/>
						<xs:enumeration value="sw"/>
						<xs:enumeration value="fp"/>
						<xs:enumeration value="sd"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xumber" use="required"/>
			<xs:attribute name="state" type="xs:string"/>
			<xs:attribute name="incomplete" type="xs:boolean"/>
			<xs:attribute name="rank" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== room-end/catalog/catalog.viewer/catalog.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="catalog.xsl"?>
<catalog xsi:noNamespaceSchemaLocation="catalog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<year y="2014">
	<!--Schwarz Weiß Negativ-->
		<film number="1444" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1444"/>
		<film number="1445" author="roumen" camera="Olympus 35 SP" type="sw" xumber="r11_1407"/>
		<film number="1446" author="roumen" camera="Canon A-1" type="sw" xumber="r11_1407"/>
		<film number="1447" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1448" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1449" author="roumen" camera="Nikon FM3a" type="sw" xumber="r11_1419"/>
		<film number="1450" author="roumen" camera="Konika Hi Matic 7s II" type="sw" xumber="r11_1429"/>
		<film number="1451" author="roumen" camera="Nikon F100" type="sw" xumber="r11_1451"/>
		<film number="1454" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
		<film number="1457" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
	<!--Farb Negativ-->
	<!--Farb Positiv-->
	</year>

	<year y="2013">
	<!--Schwarz Weiß Negativ-->
		<film number="1444" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1444"/>
		<film number="1445" author="roumen" camera="Olympus 35 SP" type="sw" xumber="r11_1407"/>
		<film number="1446" author="roumen" camera="Canon A-1" type="sw" xumber="r11_1407"/>
		<film number="1447" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1448" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1449" author="roumen" camera="Nikon FM3a" type="sw" xumber="r11_1419"/>
		<film number="1450" author="roumen" camera="Konika Hi Matic 7s II" type="sw" xumber="r11_1429"/>
		<film number="1451" author="roumen" camera="Nikon F100" type="sw" xumber="r11_1451"/>
		<film number="1454" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
		<film number="1457" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
	<!--Farb Negativ-->
	<!--Farb Positiv-->
	</year>
<!--Jahr 2012: Arthur-->
	<year y="2012">
	<!--Schwarz Weiß Negativ-->
		<film number="1435" author="roumen" camera="Canon AE-1" type="sw" xumber="i11_1435"/>
		<film number="1436" author="roumen" camera="Canon AE-1" type="sw" xumber="i11_1435"/>
		<film number="1444" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1444"/>
		<film number="1445" author="roumen" camera="Olympus 35 SP" type="sw" xumber="r11_1407"/>
		<film number="1446" author="roumen" camera="Canon A-1" type="sw" xumber="r11_1407"/>
		<film number="1447" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1448" author="roumen" camera="Canon F-1 New" type="sw" xumber="r11_1407"/>
		<film number="1449" author="roumen" camera="Nikon FM3a" type="sw" xumber="r11_1419"/>
		<film number="1450" author="roumen" camera="Konika Hi Matic 7s II" type="sw" xumber="r11_1429"/>
		<film number="1451" author="roumen" camera="Nikon F100" type="sw" xumber="r11_1451"/>
		<film number="1454" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
		<film number="1457" author="ivana" camera="Kodak Retina IIIc" type="sw" xumber="i11_1454"/>
	<!--Farb Negativ-->
	<!--Farb Positiv-->
	</year>
<!--Jahr 2011: Arthur-->
	<year y="2011">
	<!--Schwarz Weiß Negativ-->
		<film number="1418" author="roumen" camera="Leica MP" type="sw" xumber="r11_1418"/>
		<film number="1419" author="roumen" camera="Nikon FM3a" type="sw" xumber="r11_1419"/>
		<film number="1420" author="roumen" camera="Canon AE-1" type="sw" xumber="r11_1420"/>
		<film number="1421" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1421"/>
		<film number="1422" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1422"/>
		<film number="1423" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1423"/>
		<film number="1424" author="ivana" camera="Mamiya 645 Super" type="sw" xumber="i21_1424"/>
		<film number="1424" author="roumen" camera="Mamiya 645 Super" type="sw" xumber="r21_1424"/>
		<film number="1425" author="roumen" camera="Olympus OM-2n" type="sw" xumber="r11_1425"/>
		<film number="1426" author="roumen" camera="Nikon FM3a" type="sw" xumber="r11_1426"/>
		<film number="1427" author="ivana" camera="Rolleiflex 3.5 Automat II" type="sw" xumber="i31_1427"/>
		<film number="1428" author="roumen" camera="Konica Autoreflex TC" type="sw" xumber="r11_1428"/>
		<film number="1429" author="roumen" camera="Konika Hi Matic 7s II" type="sw" xumber="r11_1429"/>
		<film number="1430" author="roumen" camera="Nikon F100" type="sw" xumber="r11_1430"/>
		<film number="1431" author="roumen" camera="Olympus OM-2n" type="sw" xumber="r11_1431"/>
		<film number="1432" author="ivana" camera="Ercona II" type="sw" xumber="i61_1432"/>
		<film number="1433" author="roumen" camera="Rollei SL66" type="sw" xumber="r31_1433"/>
	<!--Farb Negativ-->
		<film number="3244" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i12_3244"/>
		<film number="3245" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i12_3244"/>
		<film number="3246" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i12_3244"/>
		<film number="3247" author="roumen" camera="Nikon F100" type="fn" xumber="i12_3244"/>
		<film number="3248" author="roumen" camera="Nikon FM3a" type="fn" xumber="i12_3244"/>
		<film number="3249" author="roumen" camera="Nikon FM3a" type="fn" xumber="i12_3244"/>
		<film number="3250" author="roumen" camera="Nikon FM3a" type="fn" xumber="i12_3244"/>
		<film number="3251" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i12_3244"/>
		<film number="3252" author="roumen" camera="Nikon FM3a" type="fn" xumber="i12_3244"/>
		<film number="3253" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i12_3244"/>
	<!--Schwarz Weiß Positiv-->
		<film number="4021" author="roumen" camera="Minolta XD7"  type="sd" xumber="r15_4021"/>
	<!--Farb Positiv-->
		<film number="2102" author="roumen" camera="Nikon FM3a" type="fn" xumber="i16_2102"/>
		<film number="2103" author="ivana" camera="Kodak Retina IIIc" type="fn" xumber="i16_2103"/>
	</year>
<!--Jahr 2010: Arthur, Nördlingen-->
	<year y="2010">
	<!--Schwarz Weiß Negativ-->
		<film number="1406" author="ivana" camera="Mamiya 645 Super" type="sw" xumber="i21_1406"/>
		<film number="1407" author="roumen" camera="Leica MP" type="sw" xumber="r11_1407"/>
		<film number="1408" author="roumen" camera="Leica MP" type="sw" xumber="r11_1408"/>
		<film number="1409" author="roumen" camera="Kodak Retina IIIc" type="sw" xumber="r11_1409"/>
		<film number="1410" author="ivana" camera="Rolleiflex 2.8E " type="sw" xumber="i21_1410"/>
		<film number="1411" author="roumen" camera="Olympus OM-1n" type="sw" xumber="r11_1411"/>
		<film number="1412" author="roumen" camera="Canon A-1" type="sw" xumber="r11_1412"/>
		<film number="1413" author="roumen" camera="Olympus OM-1nP" type="sw" xumber="r11_1413"/>
		<film number="1414" author="roumen" camera="Rollei SL66" type="sw" xumber="r11_1414"/>
		<film number="1416" author="roumen" camera="Mamiya 645 Super" type="sw" xumber="r21_1416"/>
		<film number="1417" author="roumen" camera="Mamiya 645 Super" type="sw" xumber="r21_1417"/>
	<!--Farb Negativ-->
		<film number="3237" author="roumen" camera="Leica MP" type="fn" xumber="r12_3237"/>
		<film number="3238" author="roumen" camera="Canon AE-1" type="fn" xumber="r12_3238"/>
		<film number="3239" author="ivana" camera="Minolta XD7" type="fn" xumber="i12_3239"/>
		<film number="3240" author="roumen" camera="Nikon FM3a"  type="fn" xumber="r12_3240"/>
		<film number="3241" author="ivana" camera="Minolta XD7"  type="fn" xumber="ii2_3241"/>
		<film number="3241" author="roumen" camera="Minolta XD7"  type="fn" xumber="ri2_3241"/>
		<film number="3242" author="roumen" camera="Canon A-1"  type="fn" xumber="r12_3242"/>
		<film number="3243" author="roumen" camera="Kodak Retina IIIc"  type="fn" xumber="i12_3243"/>
	<!--Farb Positiv-->
		<film number="2100" author="ivana" camera="Любитель 2" type="fp" xumber="i36_2100"/>
		<film number="2101" author="roumen" camera="Mamiya 645 Super" type="fp" xumber="r26_2101"/>
	</year>
<!--Jahr 2009: Lisboa, Arthur-->
	<year y="2009">
	<!--Schwarz Weiß Negativ-->
		<film number="1375" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1375"/>
		<film number="1376" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1376"/>
		<film number="1377" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1377"/>
		<film number="1378" author="ivana" camera="Minolta XD7" type="sw" xumber="i11_1378"/>
		<film number="1379" author="ivana" camera="Mamiya 645 Super"  type="sw" xumber="i21_1379"/>
		<film number="1381" author="roumen" camera="Leica MP" type="sw" xumber="r11_1381"/>
		<film number="1380" author="ivana" camera="Mamiya 645 Super" type="sw" xumber="i21_1380"/>
		<film number="1382" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1382"/>
		<film number="1383" author="ivana" camera="Rolleiflex 2.8E" type="sw" xumber="i31_1383"/>
		<film number="1384" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1384"/>
		<film number="1385" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1385"/>
		<film number="1386" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1386"/>
		<film number="1387" author="roumen" camera="Leica MP" type="sw" xumber="r11_1387"/>
		<film number="1388" author="roumen" camera="Leica MP" type="sw" xumber="r11_1388"/>
		<film number="1389" author="ivana" camera="Olympus OM-1N" type="sw" xumber="i11_1389"/>
		<film number="1390" author="ivana" camera="Olympus OM-1N" type="sw" xumber="i11_1390"/>
		<film number="1392" author="roumen" camera="Rolleiflex 2.8E" type="sw" xumber="r31_1392"/>
